import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Form } from "../components/Form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className={styles.title}>Pokemon Fight Simulator</h1>
        </div>
        <Form />
        <div></div>
        <div className={styles.grid}></div>
      </main>
    </div>
  );
}
